<?php

namespace AppBundle\Repository;

/**
 * AbusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbusRepository extends \Doctrine\ORM\EntityRepository
{
}
