<?php

namespace AppBundle\Repository;

/**
 * BlocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocRepository extends \Doctrine\ORM\EntityRepository
{
}
