<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{

    public function getList($max = null)
    {
        $qb = $this->createQueryBuilder('c');

        $qb->select('c.id, c.slug, c.nom')
            ->orderBy('c.id', 'DESC')
            ->setMaxResults($max);

        return $qb->getQuery()->execute();
    }

    public function myFindAll($max = null)
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.image', 'img')
            ->leftJoin('c.prestataires', 'p')
            ->select('c')
            ->addSelect('img')
            ->addSelect('p');


        return $qb->getQuery()->getArrayResult();

    }




}
