<?php

namespace AppBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{

    public function findNames($max)
    {
        $em = $this->getEntityManager();
        $noms = $em->createQuery('SELECT c.id, c.nom FROM AppBundle:Categorie c 
                                  ORDER BY c.id DESC')
            ->setMaxResults($max);
        return $noms->getResult();
    }


}
