<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{

    public function getList($max = null)
    {
        $qb = $this->createQueryBuilder('c');

        $qb->select('c.id, c.slug, c.nom')
            ->orderBy('c.id', 'DESC')
            ->setMaxResults($max);

        return $qb->getQuery()->execute();
    }

    public function myFindAll($max = null)
    {
        $qb = $this->createQueryBuilder('c');

        $qb = $this->selectImagePrestataires($qb)->orderBy('c', 'ASC');
        if (isset($max) && !empty($max)) {
            $qb->setMaxResults($max);
            return new Paginator($qb);
        }

        return $qb->getQuery()->execute();

    }

    private function selectImagePrestataires(QueryBuilder $qb)
    {
        return $qb
            ->leftJoin('c.image', 'im')
            ->addSelect('im')
            ->leftJoin('c.prestataires', 'p')
            ->addSelect('p');

    }


}
