<?php

namespace AppBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListByUser($uid)
    {

        $qb = $this->createQueryBuilder('co')
            ->andWhere('co.prestataire = :uid')
            ->setParameter('uid', $uid)
            ->addOrderBy('co.encodageDate', 'DESC');
        return $qb->getQuery()->getArrayResult();;
    }
}
