<?php

namespace AppBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFrontImages($nbre = 5)
    {
        $qb = $this->createQueryBuilder('i')
            ->select('i.url, i.imageType, i.id')
            ->join('i.prestatairePhotos', 'prest')
            ->addSelect('prest.nom')
            ->andWhere('i.imageType= :type')
            ->setParameter('type', 'photo')
            ->setMaxResults($nbre)
            ->groupBy('prest.nom')
            ->orderBy('i.id', 'DESC');

        return $qb->getQuery()->execute();


    }
}
