<?php

namespace AppBundle\Repository;

/**
 * LocaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocaliteRepository extends \Doctrine\ORM\EntityRepository
{
}
