<?php

namespace AppBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNames($max)
    {
        $em = $this->getEntityManager();
        $noms = $em->createQuery('SELECT p.id, p.nom FROM AppBundle:Promotion p ORDER BY p.id DESC')
            ->setMaxResults($max);
        return $noms->getResult();
    }
}
