<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Prestataire;

/**
 * StageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageRepository extends \Doctrine\ORM\EntityRepository
{

    public function getList($max = null)
    {
        $qb = $this->createQueryBuilder('s');

        $qb->select('s.slug, s.nom, s.fin')
            ->orderBy('s.fin', 'ASC')
            ->setMaxResults($max);

        return $qb->getQuery()->execute();

    }

    public function getListByUser($uid)
    {

        $qb = $this->createQueryBuilder('s')
            ->andWhere('s.prestataire = :uid')
           ->setParameter('uid', $uid)
           ->orderBy('s.fin', 'ASC');
;

        return $qb->getQuery()->getArrayResult();
    }

    public function myFindAll()
    {
        $qb = $this->createQueryBuilder('s')
            ->leftJoin('s.prestataire', 'p')
            ->addSelect('p');

        return $qb->getQuery()->getArrayResult();
    }

}
