<?php

namespace AppBundle\Repository;

/**
 * StageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageRepository extends \Doctrine\ORM\EntityRepository
{

    public function getList($max = null)
    {
        $qb = $this->createQueryBuilder('s');

        $qb->select('s.slug, s.nom, s.fin')
            ->orderBy('s.fin', 'ASC')
            ->setMaxResults($max);

        return $qb->getQuery()->execute();

    }

}
