<?php

namespace AppBundle\Repository;

/**
 * StageeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageeRepository extends \Doctrine\ORM\EntityRepository
{
}
