<?php

namespace AppBundle\Repository;

/**
 * UserTempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTempRepository extends \Doctrine\ORM\EntityRepository
{
}
